networks:
  chat-net:

services:
  backend:
    build: ./server
    environment:
      - MONGO_URI=mongodb://database:27017/chat
      - REDIS_HOST=message_broker
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-key
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=chat
      - MINIO_PUBLIC_ENDPOINT=192.168.1.10
    networks:
      - chat-net
    depends_on:
      - database
      - message_broker
      - minio

  client:
    build: ./web-app
    volumes:
      - ./web-app:/app
      - /app/node_modules
    networks:
      - chat-net
    expose:
      - "3000"
    depends_on:
      - backend
  
  public-businesses:
    build: ./public-businesses
    container_name: public_business_pages
    environment:
      - PORT=3001
      - NODE_ENV=production
    networks:
      - chat-net

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit_server
    networks:
      - chat-net
    ports:
      - "7880:7880"
      - "55000-55005:55000-55005/udp"
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    command: --config /etc/livekit.yaml

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-net

  message_broker:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - chat-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - chat-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chat-net
    depends_on:
      - backend
      - client
      - public-businesses

volumes:
  mongo-data:
  minio-data:
